version: '3.8'

networks:
  red-app:

volumes: #Bloque para definir los volumenes
  database-data:

services:

  rest-api:
    build: .
    ports: #puertos que estaran expuestos.
      - "8080":"8080"
    networks: #red para conectar los equipos.
      - red-app
    volumes:
      - database-data:/tmp/