version: '3.8'

services:
  rest-api:
    build: .
    ports: #puertos que estaran expuestos.
      - "8080:8080"
    networks:
      - red-app
    volumes:
      - database-data:/tmp/

networks: #bloque para las redes
  red-app:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  database-data: